package io.virandry.maska.model;

import java.util.List;

// default package
// Generated Oct 21, 2017 10:46:30 AM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", catalog = "aivindb")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class Country implements java.io.Serializable {

	private String countryId;
	private String countryName;
	@JsonIgnore
	private List<Currency> currencies;
	@JsonIgnore
	private List<Shipping> shippings;

	public Country() {
	}

	public Country(String countryId, String countryName) {
		this.countryId = countryId;
		this.countryName = countryName;
	}

	@Id

	@Column(name = "country_id", unique = true, nullable = false, length = 10)
	public String getCountryId() {
		return this.countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	@Column(name = "country_name", nullable = false, length = 100)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public List<Currency> getCurrencies() {
		return currencies;
	}

	public void setCurrencies(List<Currency> currencies) {
		this.currencies = currencies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public List<Shipping> getShippings() {
		return shippings;
	}

	public void setShippings(List<Shipping> shippings) {
		this.shippings = shippings;
	}

}
