package io.virandry.maska.model;

import java.math.BigInteger;

// default package
// Generated Oct 21, 2017 10:46:30 AM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Orderdetail generated by hbm2java
 */
@Entity
@Table(name = "orderdetail", catalog = "aivindb")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler", "modifiedBy", "modifiedTime" })
public class Orderdetail implements java.io.Serializable {

	private Integer orderDetailId;
	private Product product;
	private String subCategoryName;
	private String subDetailIdOne;
	private String subDetailIdTwo;
	private String subDetailIdThree;
	private String subDetailIdFour;
	private String subDetailIdFive;
	private String subDetailIdSix;
	private String subDetailIdSeven;
	private String subDetailIdEight;
	private Currency currency;
	private BigInteger pricePerItem;
	private int quantity;
	private BigInteger priceSubTotal;
	private Order order;
	private String modifiedBy;
	private Date modifiedTime;
	private int isActive;

	public Orderdetail() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_detail_id", unique = true, nullable = false)
	public Integer getOrderDetailId() {
		return this.orderDetailId;
	}

	public void setOrderDetailId(Integer orderDetailId) {
		this.orderDetailId = orderDetailId;
	}

	@Column(name = "sub_category_name", nullable = false, length = 100)
	public String getSubCategoryName() {
		return this.subCategoryName;
	}

	public void setSubCategoryName(String subCategoryName) {
		this.subCategoryName = subCategoryName;
	}

	@Column(name = "sub_detail_id_one", length = 10)
	public String getSubDetailIdOne() {
		return this.subDetailIdOne;
	}

	public void setSubDetailIdOne(String subDetailIdOne) {
		this.subDetailIdOne = subDetailIdOne;
	}

	@Column(name = "sub_detail_id_two", length = 10)
	public String getSubDetailIdTwo() {
		return this.subDetailIdTwo;
	}

	public void setSubDetailIdTwo(String subDetailIdTwo) {
		this.subDetailIdTwo = subDetailIdTwo;
	}

	@Column(name = "sub_detail_id_three", length = 10)
	public String getSubDetailIdThree() {
		return this.subDetailIdThree;
	}

	public void setSubDetailIdThree(String subDetailIdThree) {
		this.subDetailIdThree = subDetailIdThree;
	}

	@Column(name = "sub_detail_id_four", length = 10)
	public String getSubDetailIdFour() {
		return this.subDetailIdFour;
	}

	public void setSubDetailIdFour(String subDetailIdFour) {
		this.subDetailIdFour = subDetailIdFour;
	}

	@Column(name = "sub_detail_id_five", length = 10)
	public String getSubDetailIdFive() {
		return this.subDetailIdFive;
	}

	public void setSubDetailIdFive(String subDetailIdFive) {
		this.subDetailIdFive = subDetailIdFive;
	}

	@Column(name = "sub_detail_id_six", length = 10)
	public String getSubDetailIdSix() {
		return this.subDetailIdSix;
	}

	public void setSubDetailIdSix(String subDetailIdSix) {
		this.subDetailIdSix = subDetailIdSix;
	}

	@Column(name = "sub_detail_id_seven", length = 10)
	public String getSubDetailIdSeven() {
		return this.subDetailIdSeven;
	}

	public void setSubDetailIdSeven(String subDetailIdSeven) {
		this.subDetailIdSeven = subDetailIdSeven;
	}

	@Column(name = "sub_detail_id_eight", length = 10)
	public String getSubDetailIdEight() {
		return this.subDetailIdEight;
	}

	public void setSubDetailIdEight(String subDetailIdEight) {
		this.subDetailIdEight = subDetailIdEight;
	}

	@Column(name = "price_per_item", nullable = false)
	public BigInteger getPricePerItem() {
		return this.pricePerItem;
	}

	public void setPricePerItem(BigInteger pricePerItem) {
		this.pricePerItem = pricePerItem;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price_sub_total", nullable = false)
	public BigInteger getPriceSubTotal() {
		return this.priceSubTotal;
	}

	public void setPriceSubTotal(BigInteger priceSubTotal) {
		this.priceSubTotal = priceSubTotal;
	}

	@Column(name = "modified_by", nullable = false, length = 100)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", nullable = false, length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Column(name = "is_active", nullable = false)
	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public Order getOrder() {
		return order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "currency_id", nullable = false)
	public Currency getCurrency() {
		return currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
