package io.virandry.maska.model;


// default package
// Generated Oct 16, 2017 9:41:25 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "aivindb")
public class Product implements java.io.Serializable {

	private Integer productId;
	private String productName;
	private String productDesc;
	private String subCategoryId;
	private long price;
	private String currencyId;
	private String modifiedBy;
	private Date modifiedTime;
	private int isActive;
	private String sellPrice;
	private Integer quantity;
	private Integer preorderQuantity;

	public Product() {
	}

	public Product(String productName, String subCategoryId, long price, String currencyId, String modifiedBy,
			Date modifiedTime, int isActive) {
		this.productName = productName;
		this.subCategoryId = subCategoryId;
		this.price = price;
		this.currencyId = currencyId;
		this.modifiedBy = modifiedBy;
		this.modifiedTime = modifiedTime;
		this.isActive = isActive;
	}

	public Product(String productName, String productDesc, String subCategoryId, long price, String currencyId,
			String modifiedBy, Date modifiedTime, int isActive, String sellPrice, Integer quantity,
			Integer preorderQuantity) {
		this.productName = productName;
		this.productDesc = productDesc;
		this.subCategoryId = subCategoryId;
		this.price = price;
		this.currencyId = currencyId;
		this.modifiedBy = modifiedBy;
		this.modifiedTime = modifiedTime;
		this.isActive = isActive;
		this.sellPrice = sellPrice;
		this.quantity = quantity;
		this.preorderQuantity = preorderQuantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "product_id", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "product_name", nullable = false, length = 100)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_desc", length = 200)
	public String getProductDesc() {
		return this.productDesc;
	}

	public void setProductDesc(String productDesc) {
		this.productDesc = productDesc;
	}

	@Column(name = "sub_category_id", nullable = false, length = 10)
	public String getSubCategoryId() {
		return this.subCategoryId;
	}

	public void setSubCategoryId(String subCategoryId) {
		this.subCategoryId = subCategoryId;
	}

	@Column(name = "price", nullable = false)
	public long getPrice() {
		return this.price;
	}

	public void setPrice(long price) {
		this.price = price;
	}

	@Column(name = "currency_id", nullable = false, length = 10)
	public String getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(String currencyId) {
		this.currencyId = currencyId;
	}

	@Column(name = "modified_by", nullable = false, length = 100)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_time", nullable = false, length = 19)
	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

	@Column(name = "is_active", nullable = false)
	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	@Column(name = "sell_price", length = 100)
	public String getSellPrice() {
		return this.sellPrice;
	}

	public void setSellPrice(String sellPrice) {
		this.sellPrice = sellPrice;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "preorder_quantity")
	public Integer getPreorderQuantity() {
		return this.preorderQuantity;
	}

	public void setPreorderQuantity(Integer preorderQuantity) {
		this.preorderQuantity = preorderQuantity;
	}

}
